- src/views/dashboard/Dashboard.js
> Dashboard no longer shows collections that are archived

- src/components/modal/Modal.js
> Fixed overflow issue

- src/components/bits/LazyImage/index.jsx
- src/components/c/ManageCollection/index.jsx
- src/components/modals/components/CreateContent/index.jsx
- src/components/modals/containers/CreateContentContainer.jsx
- src/containers/c/ManageCollectionContainer.jsx
- src/services/s/content.redux.js
- successfully get a youtube thumbnail URL.
- the backend does not update the thumbnail URL (need to check when our backend sets up).
> added youtube thumbnail, need to check backend later for the update

- src/components/c/Manager/index.jsx
- src/components/modals/components/CreateContent/index.jsx
- src/components/modals/components/CreateContent/styles.js
- src/components/modals/containers/CreateContentContainer.jsx
- src/models/Content.js
- src/proxy/p/ApiProxy.js
- src/services/s/admin.redux.js
- src/services/s/content.redux.js
Thumbnail field is  a string with value empty and in the future a default thumbnail will show from the back end. Create content from resource works for instructors and for lab assistant/admin proxying as a user
> Create content from resource is working properly.

- src/components/modals/components/CreateContent/index.jsx
- src/containers/c/ManageCollectionContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/admin.redux.js
- src/services/s/content.redux.js
Fixed errors in sesison id update. Changed the way content is rendered by ManageCollection. Not using api call content get
> Fixed content session id update issues

- src/components/bits/AdminTable/index.jsx
Resolved Issue #53 
AdminTable is now able to sort by all columns including Last Login and Roles
Remove roles filter on AdminTable
> Sorting & Filter 

- src/components/bits/BlockCollection/index.jsx
- src/components/bits/ListCollection/index.jsx
Resolved issue #61 
Content is now able to be hidden from a collection if professor unpublish it
> able to publish/unpublish content from collection

- src/components/c/Controller/index.jsx
- src/components/c/NewTrackEditor/index.jsx
- src/components/c/Player/index.jsx
- src/components/c/TrackLayer/index.jsx
- src/containers/c/EventsContainer.jsx
- src/containers/c/PlayerContainer.jsx
Fixed issue of blank going away on seek while using the player. Fixed adding an event to the current time. Still working on added to a desired time. Added page reload message to the track editor when trying to exit the page
> Track editor changes

- src/components/c/CollectionPermissions/index.jsx
- src/components/c/CollectionPermissions/styles.js
- src/components/modals/components/AddBatchNetids/index.jsx
- src/components/modals/components/AddBatchNetids/styles.js
- src/components/modals/containers/AddBatchNetidsContainer.jsx
- src/components/modals/containers/HelpDocumentationContainer.jsx
- src/containers/c/CollectionPermissionsContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/collections.redux.js
Resolved issue #74 
Add "Add Many" button so admin can paste a list of netids
> Collection permissions

- src/components/c/Menu/index.jsx
- src/containers/c/CollectionsContainer.jsx
- src/containers/c/ManagerContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/collections.redux.js
Merging changes to the player. 
The player component had the transcript as just a div, so I created a new component to decrease the component size. 
Collections from courses were not displaying in the collections. So, I had to create logic in the collection services to get collections from the courses.
> Transcript

- package-lock.json
- package.json
- src/components/bits/Transcript/index.jsx
- src/components/bits/Transcript/styles.js
- src/components/c/ContentOverview/index.jsx
- src/containers/c/CollectionsContainer.jsx
- src/containers/c/ContentOverviewContainer.jsx
- src/containers/c/PlayerContainer.jsx
- src/models/BackEndContent.js
- src/models/Content.js
- src/services/s/content.redux.js
Added highlights to the transcript. Finished regular expression and tested for specific cases where a non word would account as valid. Added a way for professors to add important words to a collection. Tested adding and removing words. Adding words function was added to the content overview component
> Finished word highlights

- src/components/bits/Transcript/index.jsx
- src/components/bits/Transcript/styles.js
- src/components/c/Menu/index.jsx
- src/components/c/NewTrackEditor/index.jsx
Finished translation functionality. Translates words from spanish russian and german for now.
> Translation

- src/components/c/Menu/index.jsx
delete "About Us," "Contact Us," and "Feedback/ Issue", only leave Contact Us under footnote
> delete "About Us," "Contact Us," and "Feedback/ Issue"

- src/components/c/CollectionPermissions/index.jsx
- src/components/c/CollectionPermissions/styles.js
- src/components/modals/containers/FileUploadContainer.jsx
- src/containers/c/CollectionPermissionsContainer.jsx
- src/containers/c/ResourceOverviewContainer.jsx
- src/models/Content.js
- src/proxy/p/ApiProxy.js
- src/services/s/auth.redux.js
- src/services/s/file.redux.js
- bugfix on get collection 
- resolve merge conflict
- added first draft of collection permissions
> fix bugs and minor errors

- src/components/c/CollectionPermissions/index.jsx
- src/components/c/ContentOverview/index.jsx
- src/components/c/ContentOverview/styles.js
- src/components/modals/components/CreateContent/index.jsx
- src/components/modals/components/CreateContent/styles.js
- src/components/modals/containers/CreateContentContainer.jsx
- src/components/modals/containers/FileUploadContainer.jsx
- src/containers/c/CollectionPermissionsContainer.jsx
- src/containers/c/ResourceOverviewContainer.jsx
- src/models/BackEndContent.js
- src/proxy/p/ApiProxy.js
- src/services/s/resources.redux.js
- fixed error during file upload
- fixed error from creating content with a resource file
> fixed bugs on file upload and creating content with resource.

- src/components/c/ContentOverview/index.jsx
- src/containers/c/LabAssistantManagerContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/admin.redux.js
- src/services/s/content.redux.js
> Esdras production fixes

- src/components/bits/Bar/styles.js
- src/components/bits/Transcript/index.jsx
- src/components/c/ContentOverview/index.jsx
- src/components/c/ContentOverview/styles.js
- src/components/c/Controller/index.jsx
- src/components/c/ManageCollection/index.jsx
- src/components/c/Player/index.jsx
- src/containers/c/ContentOverviewContainer.jsx
Changed issue with react creating over 200 new html/css classes in th…e Bar component.
Fixed issue in transcript where displaySubtitles might be undefined.
Added logic in content overview and ManageCollection in order to support expired content.
Got rid of carat in the controller next to the play button.
> Production fixes and added expired content support

- src/components/c/CollectionPermissions/index.jsx
- src/containers/c/CollectionPermissionsContainer.jsx
- src/containers/c/ManageResourceContainer.jsx
- src/containers/c/ResourceOverviewContainer.jsx
- fixed not updating add and delete after adding user
- fixed rendering error on resource page
> fixed bugs on permissions page and resource page

- src/components/bits/ListCollection/index.jsx
- src/components/c/Collections/index.jsx
- src/components/c/Collections/styles.js
- src/components/c/PublicListCollection/index.jsx
- src/components/c/SearchPublicCollections/index.jsx
- src/components/c/SearchPublicCollections/styles.js
- src/components/modals/containers/MorePublicCollectionsContainer.jsx
- src/containers/c/CollectionsContainer.jsx
- src/containers/c/PublicListCollectionContainer.jsx
- src/containers/c/SearchPublicCollectionsContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/admin.redux.js
- src/services/s/collections.redux.js
- changed search method
- fixed subscribtion
- changed layout
> updated public collection

- src/components/c/Collections/index.jsx
- src/components/c/Collections/styles.js
- src/components/c/PublicManager/index.jsx
- src/containers/c/ManageCollectionContainer.jsx
- src/containers/c/ManagerContainer.jsx
- src/containers/c/PublicManagerContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/collections.redux.js
- fixed not switching to collection immediately after creating a collection (collection, public collection).
- fixed collection name not switching to the current collection's title name.
- combine public collections and buy collections
> fixed collections and public collections minor errors

- src/components/c/Admin/index.jsx
- src/components/c/Admin/styles.js
- src/components/c/CollectionPermissions/index.jsx
- src/components/c/Collections/styles.js
- src/components/c/ManageResource/index.jsx
- src/components/c/ManageResource/styles.js
- src/components/modals/components/AddBatchNetids/index.jsx
- src/components/modals/components/AddUsers/index.jsx
- src/components/modals/components/AddUsers/styles.js
- src/components/modals/containers/AddBatchNetidsContainer.jsx
- src/components/modals/containers/AddUsersContainer.jsx
- src/containers/c/AdminContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/admin.redux.js
- update admin dashboard with add-users feature
- update adding resource with netid and checking its validation
- fixed UI on search resource
- fixed UI on public collection
> update admin dashboard with add-users feature

- src/components/bits/TrackEditorSideMenu/index.jsx
- src/components/c/NewVideoEditor/index.jsx
- src/components/c/SubtitleEditor/index.js
> fixed video editor comment error

- src/components/bits/Bar/index.jsx
- src/components/c/Player/index.jsx
- src/components/c/VideoContainer/index.jsx
> Christian timing

- src/components/bits/Bar/index.jsx
- src/components/c/ClipEditor/index.jsx
- src/components/c/ClipEditor/styles.js
- src/components/c/Controller/index.jsx
- src/components/c/Controller/styles.js
- src/components/c/VideoEditor/index.jsx
> Anita time

- src/components/c/Controller/index.jsx
- src/components/c/VideoEditor/index.jsx
- src/containers/c/EventsContainer.jsx
- src/containers/c/SubtitlesEditorContainer.jsx
fix not updateing subtitle
fix timing
> disable comment

- src/proxy/p/ApiProxy.js
- src/services/s/admin.redux.js
Changed user delete endpoint to point towards deleting users and alll the collections
> Esdras user delete

- src/components/c/VideoEditor/index.jsx
Export annotations is working. Current download is stored in a json file.
> Esdras export annotations done

- src/components/bits/EventCard/index.jsx
- src/components/c/TrackLayer/index.jsx
- src/components/c/VideoContainer/index.jsx
- src/components/c/VideoContainer/styles.js
- src/components/c/VideoEditor/index.jsx
- src/components/c/VideoEditor/styles.js
1. Remove unused scroll bar since it was buggy.
2. Added a time indicator shadow to let our current RED time indicator stay in place and show the blue one on hover.
3. Added javascript DOM manupulation code to change the DOM and the time indicator shadow to showcase new times and X axis offset
4. Added a new time display to indicate the seek time during the hover event
5. I did not add the hover event to the layers, but I added it to the actual time bar. Added the hover event to the layers causes many issues.
6. Changed style formats to match new layout and got rid off some unused code
#215
> New Scrubber changes and hovering effect

- src/components/bits/PlayerControls/index.jsx
- src/components/bits/PlayerControls/styles.js
- src/components/c/Player/index.jsx
- src/containers/c/PlayerContainer.jsx
> add time to player

- public/index.html
- src/__tests__/components/bits/Transcript/index.test.jsx
- src/assets/skip-back-white.svg
- src/assets/skip-back.svg
- src/assets/skip-forward-white.svg
- src/components/bits/PlayerControls/index.jsx
- src/components/bits/PlayerControls/styles.js
- src/components/bits/Transcript/index.jsx
- src/components/bits/Transcript/styles.js
- src/components/c/Header/styles.js
- src/components/c/Manager/index.jsx
- src/components/c/Player/index.jsx
- src/components/c/Player/styles.js
- src/containers/c/LabAssistantManagerContainer.jsx
- src/containers/c/ManagerContainer.jsx
- src/containers/c/PlayerContainer.jsx
- src/containers/c/PlayerSubtitlesContainer.jsx
- src/services/s/admin.redux.js
Fix #348, #347 
Added new buttons to go over subtitles in the player. Added new icons, and created a new way to scroll automatically through the subtitles.
> Esdras transcript

- src/components/bits/PlayerControls/index.jsx
- src/components/bits/Tooltips/index.jsx
- src/components/c/SubtitleEditor/styles.js
This branch should have been called icons-player-bug, but regardless, the commit message says it all, I fixed it so that the seek buttons don't appear if there are no captions.
> 376 icons subtitle editor bug

- src/__tests__/components/c/VideoContainer/index.test.jsx
- src/components/c/VideoContainer/index.jsx
This is just the commented out code, going to make a new issue that actually deals with fixing the hotkeys.
> Commented out the bugged code for easy access

- src/components/modals/components/CreateContent/index.jsx
This fixed the search resources and the create new context description boxes
> BiggerBox New commit

- src/components/c/Feedback/index.jsx
Added `[Y-video] ` to the subjects of every email that comes from the Feedback page
> 409 feedback subject change

- src/__tests__/containers/c/ContentOverviewContainer.test.jsx
- src/__tests__/containers/c/ManageCollectionContainer.test.jsx
- src/components/bits/Tooltips/styles.js
- src/components/c/ContentOverview/index.jsx
- src/components/c/ContentOverview/styles.js
- src/components/c/ManageCollection/index.jsx
- src/components/c/ManageCollection/styles.js
These are changes to the save buttons in Manage Collections and fixing the menu tooltip/ newcontent tooltip
> Tooltip, saveicons

- src/components/c/Player/index.jsx
- src/components/c/SubtitleEditor/index.jsx
- src/components/c/VideoContainer/index.jsx
> fixed muting in player and video container

- src/components/c/Menu/index.jsx
- src/containers/c/MenuContainer.jsx
- src/services/s/interface.redux.js
Co-authored-by: Aaron Anderson <Aaron-M-Anderson@users.noreply.github.com>
> MenuToggle fix

- src/__tests__/components/c/VideoEditor/index.test.jsx
- src/components/bits/EventCard/styles.js
- src/components/bits/Transcript/index.jsx
- src/components/c/SubtitleEditor/index.jsx
- src/components/c/TrackLayer/index.jsx
- src/components/c/TrackLayer/styles.js
- src/components/c/VideoEditor/index.jsx
- src/components/c/VideoEditor/styles.js
- src/containers/c/VideoEditorContainer.jsx
Fixed subtitles jumping, zoom problems in video, wrong scrollbar size, and line styling issue in events layer
> Fixed layer and editor issues

- src/components/bits/Bar/index.jsx
- src/components/c/ClipEditor/index.jsx
- src/components/c/Player/index.jsx
- src/components/c/SubtitleEditor/index.jsx
- src/components/c/VideoContainer/index.jsx
Also wrapped in some minor changes to keep the warnings clear with recent changes from Faline
> 441 clip manager scrubber

- src/containers/c/CollectionsContainer.jsx
- src/proxy/p/ApiProxy.js
- src/services/s/auth.redux.js
Fixed call to get TA permissions.
This might need to get call in other places to determine if a student is a TA. This only has the call in the collections page.
> Fixed call for ta permissions

- src/models/Content.js
Fix regex so that empty JSON array is captured.
> fix annotations regex

- src/components/c/SkipLayer/index.jsx
- src/components/c/SubtitleEditor/index.jsx
- src/containers/c/PlayerSubtitlesContainer.jsx
- src/containers/c/SubtitlesContainer.jsx
- src/containers/c/VideoEditorContainer.jsx
I got rid of all the warnings and errors that appear in the console for all the editors, aside from the YouTube and Google ones...
> Removed quite a few nasty warnings and errors

- src/components/c/Player/index.jsx
Reverts BYU-ODH/yvideo-client#510
> Revert "config ios change"

- package-lock.json
- package.json
Fix https://github.com/BYU-ODH/yvideo-client/security/dependabot/40
> remove axois

- src/__tests__/components/bits/AdminTable/index.test.jsx
- src/__tests__/containers/c/BreadcrumbContainer.test.jsx
- src/components/c/SubtitleEditor/index.jsx
- src/components/c/SubtitleEditor/styles.js
- src/components/modals/containers/CreateContentContainer.jsx
> 549 subtitle editor sublayer

- src/components/c/TrackLayer/styles.js
- src/components/c/VideoContainer/styles.js
- src/components/c/VideoEditor/index.jsx
fixed scrubber and layer oversize issue
> scrubber problem

- src/components/c/Collections/index.jsx
- src/components/modals/components/CreateContent/index.jsx
- src/components/modals/components/CreateContent/styles.js
- src/components/modals/containers/CreateContentContainer.jsx
With Both LabAssistantManager's Content Creation and also regular manager
> Fixed the various issues

- package.json
- src/components/c/ClipEditor/index.jsx
- src/components/c/SubtitleEditor/index.jsx
- src/components/c/VideoEditor/index.jsx
- src/components/vanilla_scripts/debounce/.internal/freeGlobal.js
- src/components/vanilla_scripts/debounce/.internal/root.js
- src/components/vanilla_scripts/debounce/debounce.js
- src/components/vanilla_scripts/debounce/isObject.js
- src/components/vanilla_scripts/editorCommon.js
- src/containers/c/BlockCollectionContainer.jsx
Implemented the debounce across all 3 editors
> Debounced all the zoom scrolls

- src/components/c/VideoEditor/index.jsx
- src/components/modals/components/SubtitlesModal/index.jsx
- src/components/vanilla_scripts/editorCommon.js
> hotfix && fixed File Importing

- src/components/bits/Bar/styles.js
Change the color from bar for skips
> 763 Change color in bar for skips

- src/components/c/ContentOverview/index.jsx
- src/containers/c/ContentOverviewContainer.jsx
- src/containers/c/PlayerContainer.jsx
> 598 Editing name content error prevent automatic close

- src/components/bits/Transcript/styles.js
> 775 Change size transcript container and box

- src/components/c/SubtitleEditor/index.jsx
- src/components/c/VideoContainer/index.jsx
- src/components/modals/containers/CreateContentContainer.jsx
- src/models/Content.js
- src/proxy/p/ApiProxy.js
Change all the alert native message for Sweetalert
> 774 Change all alert message for sweetalert message

- src/components/bits/SwitchToggle/styles.js
- src/components/c/CollectionPermissions/index.jsx
- src/components/c/CollectionPermissions/styles.js
...to make the Edit User Access page more usable and readable
> CSS and visual changes
